# Generated by Django 4.1.2 on 2022-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
