# Generated by Django 4.1.2 on 2022-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_house_owner_id_house_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
