# Generated by Django 4.1.2 on 2022-11-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_house_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='houses.house')),
            ],
        ),
    ]
