# Generated by Django 4.1.2 on 2022-11-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
