# Generated by Django 4.1.2 on 2022-11-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='id_house',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
