# Generated by Django 4.1.2 on 2022-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_house_id_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id_house',
            field=models.IntegerField(null=True),
        ),
    ]
