# Generated by Django 4.1.2 on 2022-11-01 16:30

from django.db import migrations, models
import django.utils.timezone
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_alter_house_id_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimage',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='houseimage',
            name='url',
        ),
        migrations.AddField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=houses.models.scramble_uploaded_filename, verbose_name='Uploaded image'),
            preserve_default=False,
        ),
    ]
