# Generated by Django 4.1.2 on 2022-11-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_remove_houseimage_extension_remove_houseimage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_id', to='houses.house'),
        ),
    ]
